server:
  port: 8180
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ONLINE_SHOP
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
#  thymeleaf:
#    check-template-location: true
#    servlet:
#      content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: HTML5
#    suffix: .html
#    prefix: classpath:/templates/